name: Test

on:
  push:
    branches: [main]
    paths_ignore: ["**.md"]
  pull_request:
    paths_ignore: ["**.md"]
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: asdf-vm/actions/plugin-test@v3
      with:
        command: helmfile --version
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - run: make lint
